# Package stage
FROM adoptopenjdk/openjdk11:latest
COPY /target/kafka-data-pipelines-1.0-jar-with-dependencies.jar /usr/local/app/kafka-data-pipelines.jar

RUN cd /usr/local/app/ && \
    wget --no-verbose https://apache.mirror.iphh.net/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2-scala2.13.tgz && \
    tar -xvzf spark-3.2.0-bin-hadoop3.2-scala2.13.tgz && \
    mv spark-3.2.0-bin-hadoop3.2-scala2.13 spark && \
    rm spark-3.2.0-bin-hadoop3.2-scala2.13.tgz