# Package stage
FROM adoptopenjdk/openjdk11:alpine
WORKDIR /usr/local/app
COPY /target/kafka-data-pipelines-1.0-jar-with-dependencies.jar /usr/local/app/kafka-data-pipelines.jar

RUN wget https://apache.mirror.iphh.net/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2-scala2.13.tgz && \
    tar -xvzf spark-3.2.0-bin-hadoop3.2-scala2.13.tgz && \
    mv spark-3.2.0-bin-hadoop3.2-scala2.13 spark && \
    rm spark-3.2.0-bin-hadoop3.2-scala2.13.tgz \

RUN apk update && apk add bash

# keep container alive
CMD java -cp /usr/local/app/kafka-data-pipelines.jar com.github.mingyima.kafka.producer.Producer